import React from 'react';
import Head from 'next/head';

import Navbar from './Navbar';
import Footer from './Footer';

const Layout = ({ children }) => {
  return (
    <div className='layout'>
      <Head>
        <title>Ecommerce Next JS | Sanity CMS</title>
        <header>
          <Navbar />
        </header>
        <main className='main-container'>{children}</main>
        <footer>
          <Footer />
        </footer>
        {/* <meta name='description' content='Generated by create next app' /> */}
      </Head>
    </div>
  );
};

export default Layout;
